### ISSUE TITLE
column \"likes\" does not exist

### ISSUE THREAD

**Issue by jforaker** [jonathan-casarrubias/loopback-likes-mixin#1]
After I added the configs per the docs, i get this error on GET of my model:

```
{
  "error": {
    "name": "error",
    "status": 500,
    "message": "column \"likes\" does not exist",
    "length": 98,
    "severity": "ERROR",
    "code": "42703",
    "position": "30",
    "file": "parse_relation.c",
    "line": "2892",
    "routine": "errorMissingColumn",
    "stack": "error: column \"likes\" does not exist\n    at Connection.parseE (/Users/jakeforaker/dev/loopback/supergleu/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/Users/jakeforaker/dev/loopback/supergleu/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/Users/jakeforaker/dev/loopback/supergleu/node_modules/pg/lib/connection.js:105:22)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    at TCP.onread (net.js:523:20)"
  }
}
```

**Comment by jonathan-casarrubias** [comment]
~~Hey @jforaker are you using a sql db? this was tested in nonsql db, I will add the property definition that should fix it~~

Ok I just reviewed the code, and there is actually a property definition for the likes column, I thought I forgot but I did not [Definition Line](https://github.com/jonathan-casarrubias/loopback-likes-mixin/blob/master/dist/likes.js#L37).

So, since I know devs using a sql kind of db, you need to [auto-migrate](https://docs.strongloop.com/display/public/LB/Implementing+auto-migration) in order for loopback to create the column in the table.

Hope it helps!!

Jon
